import {esc,client} from './live-client.mjs';
export const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
export const attendanceLabels={present:'Présent',absent:'Absent',late:'En retard'};
export function localAttendance(key){
 const read=()=>JSON.parse(localStorage.getItem(key+':attendance-v1')||'{}');
 return {async load(){return read()},async save(classId,date,rows,revision=0){const db=read(),id=classId+'/'+date;if((db[id]?.revision||0)!==revision)throw Error('L’appel a été modifié. Fermez puis rouvrez pour actualiser.');db[id]={classId,date,rows,revision:revision+1,updatedAt:new Date().toISOString()};localStorage.setItem(key+':attendance-v1',JSON.stringify(db));return db[id]}};
}
export function remoteAttendance({organization,token}={}){
 async function rpc(action,payload){let data,error;if(token){const r=await fetch('https://pasgxojzybmvbjhuokkk.supabase.co/rest/v1/rpc/quran_attendance',{method:'POST',headers:{apikey:'sb_publishable_JfiHxlqfI8pXr4Emho4vOw_QBePfSHm','Content-Type':'application/json'},body:JSON.stringify({action,payload,token}),cache:'no-store'});data=await r.json();if(!r.ok)throw Error(data.message||'Appel indisponible')}else{({data,error}=await client().rpc('quran_attendance',{action,payload:{...payload,organization}}));if(error)throw error}return data}
 return {load:()=>rpc('load',{}),save:(classId,date,rows,revision)=>rpc('save',{classId,date,rows,revision})};
}
function style(){if(document.querySelector('[data-attendance-style]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href=new URL('./attendance.css',import.meta.url);l.dataset.attendanceStyle='';document.head.append(l)}
export async function openAttendance(c,adapter){
 style();const d=document.createElement('dialog');d.className='at-dialog';d.setAttribute('aria-label','Faire l’appel');document.body.append(d);let records={},date=today(),draft={},busy=false,dirty=false;
 d.onclose=()=>d.remove();d.addEventListener('cancel',e=>{if(busy||dirty){e.preventDefault();d.querySelector('[role=status]').textContent='Enregistrez votre appel ou utilisez « Fermer sans enregistrer ».'}});
 function pick(){draft=structuredClone(records[c.id+'/'+date]?.rows||{});dirty=false}
 function draw(){d.innerHTML=`<header><div><small>APPEL FACULTATIF</small><h2>${esc(c.name)}</h2></div><button type="button" data-close>${dirty?'Fermer sans enregistrer':'Fermer'}</button></header><label>Date du cours<input type="date" value="${date}" max="${today()}" required></label><p>Sans appel enregistré, aucun élève n’est considéré absent.</p><button type="button" data-all>Tous présents</button><form>${c.students.map(s=>{const r=draft[s.id]||{};return `<fieldset data-pupil="${esc(s.id)}"><legend>${esc(s.name)}</legend><div class="at-options">${Object.entries(attendanceLabels).map(([v,l])=>`<label><input type="radio" name="status-${esc(s.id)}" value="${v}" ${r.status===v?'checked':''}>${l}</label>`).join('')}</div><label class="at-justified"><input type="checkbox" ${r.justified?'checked':''}>Absence justifiée</label><label>Petite note (facultatif)<input type="text" maxlength="240" value="${esc(r.note||'')}"></label></fieldset>`}).join('')}<p role="status" aria-live="polite"></p><button class="at-save" ${c.students.length?'':'disabled'}>Enregistrer l’appel</button></form><details><summary>Historique des élèves</summary>${c.students.map(s=>{const list=Object.values(records).filter(r=>r.classId===c.id&&r.rows[s.id]).sort((a,b)=>b.date.localeCompare(a.date));return `<section><h3>${esc(s.name)}</h3>${list.map(r=>`<p>${r.date.split('-').reverse().join('/')} · ${attendanceLabels[r.rows[s.id].status]}${r.rows[s.id].justified?' · justifiée':''}${r.rows[s.id].note?' — '+esc(r.rows[s.id].note):''}</p>`).join('')||'<p>Aucun appel renseigné.</p>'}</section>`}).join('')}</details>`;
 d.querySelector('[data-close]').onclick=()=>d.close();d.querySelector('[type=date]').onchange=e=>{if(!e.target.value||e.target.value>today()||dirty){e.target.value=date;d.querySelector('[role=status]').textContent=dirty?'Enregistrez les modifications avant de changer de date.':'Choisissez une date passée ou aujourd’hui.';return}date=e.target.value;pick();draw()};
 d.querySelector('[data-all]').onclick=()=>{c.students.forEach(s=>draft[s.id]={status:'present',justified:false,note:draft[s.id]?.note||''});dirty=true;draw()};
 d.querySelectorAll('fieldset').forEach(f=>{const id=f.dataset.pupil;f.onchange=()=>{draft[id]={status:f.querySelector('[type=radio]:checked')?.value,justified:f.querySelector('[type=checkbox]').checked,note:f.querySelector('[type=text]').value.trim()};if(draft[id].status!=='absent'){draft[id].justified=false;f.querySelector('[type=checkbox]').checked=false}dirty=true;d.querySelector('[data-close]').textContent='Fermer sans enregistrer'};f.querySelector('[type=text]').oninput=f.onchange});
 d.querySelector('form').onsubmit=async e=>{e.preventDefault();if(busy)return;const status=d.querySelector('[role=status]');if(c.students.some(s=>!attendanceLabels[draft[s.id]?.status])){status.textContent='Choisissez une présence pour chaque élève, ou « Tous présents ».';return}busy=true;d.querySelectorAll('button,input').forEach(x=>x.disabled=true);try{const rows=Object.fromEntries(c.students.map(s=>[s.id,draft[s.id]]));const r=await adapter.save(c.id,date,rows,records[c.id+'/'+date]?.revision||0);records[c.id+'/'+date]=r;dirty=false;draw();d.querySelector('[role=status]').textContent='Appel enregistré. Le directeur peut le consulter.'}catch(error){status.textContent=error.message}finally{busy=false;d.querySelectorAll('button,input').forEach(x=>x.disabled=false)}};
 }
 d.innerHTML='<p role="status">Chargement de l’appel…</p><button>Fermer</button>';d.querySelector('button').onclick=()=>d.close();d.showModal();try{records=await adapter.load();if(!d.isConnected)return;pick();draw()}catch(e){d.querySelector('[role=status]').textContent=e.message}
}
export async function mountAttendanceSummary(root,classes,load){style();let records;root.innerHTML='<p role="status">Chargement des présences…</p>';try{records=await load()}catch(e){root.textContent=e.message;return}let date=today();function draw(){const calls=Object.values(records).filter(r=>r.date===date),rows=calls.flatMap(r=>Object.values(r.rows));root.innerHTML=`<h3>Présences du jour</h3><label>Date du cours<input type="date" value="${date}" max="${today()}"></label><p>${calls.length} / ${classes.length} classes : appel renseigné · ${rows.filter(r=>r.status==='absent').length} absent(s) · ${rows.filter(r=>r.status==='late').length} retard(s)</p><div class="school-grid">${classes.map(c=>{const r=calls.find(r=>r.classId===c.id);return `<article><h3>${esc(c.name)}</h3><p>${r?'Appel renseigné':'Appel non renseigné'}</p>${r?c.students.filter(s=>r.rows[s.id]).map(s=>`<p><strong>${esc(s.name)}</strong> · ${attendanceLabels[r.rows[s.id].status]}${r.rows[s.id].justified?' · justifiée':''}${r.rows[s.id].note?' — '+esc(r.rows[s.id].note):''}</p>`).join(''):''}<details><summary>Historique des absences et retards</summary>${Object.values(records).filter(x=>x.classId===c.id).sort((a,b)=>b.date.localeCompare(a.date)).flatMap(x=>c.students.filter(s=>x.rows[s.id]&&x.rows[s.id].status!=='present').map(s=>`<p>${x.date.split('-').reverse().join('/')} · ${esc(s.name)} · ${attendanceLabels[x.rows[s.id].status]}${x.rows[s.id].justified?' · justifiée':''}</p>`)).join('')||'<p>Aucune absence ni retard renseigné.</p>'}</details></article>`}).join('')}</div>`;root.querySelector('input').onchange=e=>{date=e.target.value||today();draw()}}draw()}
