import {portal,esc,page,message,copyInvitation,downloadCsv} from './live-client.mjs';
import {createAdminMotion,icon} from './platform-admin-motion.mjs';
const names={active:'Active',trial:'Essai actif',suspended:'Suspendue / à activer',expired:'Expirée',pending:'En attente',accepted:'Acceptée',revoked:'Révoquée',owner:'Responsable',manager:'Gestionnaire',teacher:'Professeur'};
const plans={class:'Professeur indépendant',school:'École',association:'Association'};
const date=v=>v?new Date(v.slice(0,10)+'T12:00:00').toLocaleDateString('fr-FR'):'—';
const tomorrow=days=>new Date(Date.now()+days*86400000).toISOString().slice(0,10);
export async function mountLiveAdmin(root,profile={}){
 root.id='quranPlatformRoot';
 let data,tab='home',selection='',busy=false,motion,query='';
 const org=id=>data.organizations.find(o=>o.id===id),license=id=>data.licenses.find(l=>l.organization_id===id);
 const classes=id=>data.classes.filter(c=>c.organization_id===id&&c.is_active),students=id=>data.students.filter(s=>s.organization_id===id&&s.is_active);
 const active=l=>l&&['active','trial'].includes(l.status)&&l.starts_at<=tomorrow(0)&&l.expires_at>=tomorrow(0);
 const status=l=>!l?'À activer':l.expires_at<tomorrow(0)?'Expirée':names[l.status];
 const button=(title,action,id='')=>`<button class="qa-button secondary" data-action="${action}" data-id="${id}">${title}</button>`;
 const tabs=[['home','Accueil'],['organizations','Structures'],['users','Accès'],['licenses','Licences'],['activity','Historique']];
 root.innerHTML=`<div class="qa-atmosphere" aria-hidden="true"><i></i><i></i></div><section class="qa-hero qa-hero-compact"><div class="qa-hero-copy"><p class="qa-kicker">${icon('leaf')} Votre espace réel</p><h2>Bonjour ${esc((profile.name||profile.full_name||'').split(' ')[0])},<br><span>tout commence ici.</span></h2><p>Vos structures, vos accès et vos licences.<br>Les changements sont enregistrés en ligne.</p><div class="qa-hero-actions">${button('+ Créer une structure','create')}<a class="qa-button secondary" href="${page('demonstration.html')}" target="_blank" rel="noopener">Présenter la démonstration ↗</a></div></div><figure class="qa-hero-art"><img src="${new URL('../coran/art/tree-blossom.png',import.meta.url)}" width="180" height="190" alt="Un arbre en fleurs"></figure></section><nav class="qa-tabs qa-main-nav" aria-label="Administration Coran">${tabs.map(([id,label])=>`<button class="qa-tab" data-tab="${id}">${label}</button>`).join('')}</nav><div class="qa-context"><span>Données réelles · accès sécurisé</span>${button('Actualiser','refresh')}</div><p id="live-status" role="status" aria-live="polite"></p><div class="qa-workspace"></div><div class="qa-modal-host"></div><div class="qa-toast" role="status"></div>`;
 motion=createAdminMotion(root,{closeModal:()=>{selection='';root.querySelector('.qa-modal-host').innerHTML='';motion.syncModal(false,true)},moveTask:()=>{}});
 const notify=text=>root.querySelector('#live-status').textContent=text;
 function render(){
  root.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-current',b.dataset.tab===tab?'page':'false'));
  const panel=root.querySelector('.qa-workspace');
  const list=data.organizations.filter(o=>(o.name+' '+o.contact_email).toLowerCase().includes(query.toLowerCase()));
  const empty=`<article class="qa-card"><h3>Votre espace est prêt</h3><p>Aucune structure réelle pour le moment. Créez la première structure, activez sa licence puis préparez l’accès de son responsable.</p>${button('Créer ma première structure','create')}</article>`;
  if(tab==='home')panel.innerHTML=`<div class="qa-stats">${[[data.organizations.length,'structures'],[data.members.filter(m=>m.is_active&&m.role==='teacher').length,'professeurs'],[data.classes.filter(c=>c.is_active).length,'classes'],[data.students.filter(s=>s.is_active).length,'élèves'],[data.licenses.filter(active).length,'licences actives']].map(([n,label])=>`<article class="qa-stat"><strong>${n}</strong><small>${label}</small></article>`).join('')}</div>${data.organizations.length?`<article class="qa-card"><h3>Licences à vérifier</h3>${data.organizations.filter(o=>!active(license(o.id))).map(o=>`<div class="qa-setting-row"><div><strong>${esc(o.name)}</strong><small>${status(license(o.id))}</small></div>${button('Gérer la licence','open',o.id)}</div>`).join('')||'<p>Toutes les licences sont actives.</p>'}</article>`:empty}<article class="qa-card qa-subsection"><h3>Un espace de présentation à part</h3><p>La démonstration contient uniquement des exemples. Elle ne modifie jamais vos vrais comptes, classes ou licences.</p><a class="qa-button secondary" href="${page('demonstration.html?view=admin')}" target="_blank" rel="noopener">Montrer le tableau de bord de démonstration ↗</a></article>`;
  if(tab==='organizations'||tab==='licenses')panel.innerHTML=`<div class="qa-page-head"><div><h3>${tab==='licenses'?'Licences':'Structures'}</h3><p>Activez l’accès avec une capacité et une date de fin. Aucun paiement n’est prélevé ici.</p></div>${button('+ Créer une structure','create')}</div><label>Rechercher<input class="qa-input" id="live-search" type="search" value="${esc(query)}"></label><div class="qa-list">${list.map(o=>{const l=license(o.id);return `<article class="qa-org qa-org-v2"><div class="qa-org-main"><span class="qa-avatar">🏫</span><div><strong>${esc(o.name)}</strong><small>${esc(o.contact_name)} · ${esc(o.contact_email)}</small></div></div><div class="qa-metric"><strong>${classes(o.id).length}</strong><small>classes</small></div><div class="qa-metric"><strong>${students(o.id).length}/${l?.student_limit||0}</strong><small>élèves</small></div><span class="qa-pill ${active(l)?'active':'pending'}">${status(l)}</span>${button('Gérer','open',o.id)}</article>`}).join('')||empty}</div>`;
  if(tab==='users')panel.innerHTML=`<div class="qa-page-head"><div><h3>Accès et invitations</h3><p>Les invitations sont nominatives. Copiez le lien et transmettez-le à la personne concernée.</p></div></div><div class="qa-list">${data.members.map(m=>`<article class="qa-user-row"><div><strong>${esc(m.full_name||m.email)}</strong><small>${esc(m.email)} · ${esc(org(m.organization_id)?.name)}</small></div><span>${names[m.role]||m.role}</span><span>${m.is_active?'Actif':'Suspendu'}</span>${button(m.is_active?'Suspendre cet accès':'Réactiver cet accès','member',m.organization_id+':'+m.profile_id)}</article>`).join('')||'<p>Aucun accès accepté pour le moment.</p>'}</div><h3>Invitations</h3>${data.invites.map(i=>`<article class="qa-invite-row"><div><strong>${esc(i.display_name||i.email)}</strong><small>${esc(i.email)} · ${esc(org(i.organization_id)?.name)}</small></div><span>${i.status==='pending'&&new Date(i.expires_at)<new Date()?'Expirée':names[i.status]||i.status} · ${date(i.expires_at)}</span>${i.status==='pending'?button('Révoquer','revoke',i.id):''}</article>`).join('')}`;
  if(tab==='activity')panel.innerHTML=`<div class="qa-page-head"><h3>Historique réel</h3>${button('Exporter les structures','export')}</div><div class="qa-card">${data.activity.map(a=>`<div class="qa-setting-row"><div><strong>${esc(({create_organization:'Structure créée',request_access:'Demande d’accès reçue',set_license:'Licence mise à jour',invite:'Invitation créée',accept_invite:'Invitation acceptée',save_class:'Classe et apprentissages enregistrés',set_member:'Accès modifié',revoke_invite:'Invitation révoquée'})[a.action]||a.action)}</strong><small>${esc(org(a.organization_id)?.name||'Plateforme')}</small></div><time>${new Date(a.created_at).toLocaleString('fr-FR')}</time></div>`).join('')||'<p>Les premières actions apparaîtront ici.</p>'}</div>`;
  motion.decorate(panel);motion.enter(panel);motion.indicator();
  const input=root.querySelector('#live-search');if(input)input.oninput=()=>{const pos=input.selectionStart;query=input.value;render();const next=root.querySelector('#live-search');next.focus();next.setSelectionRange(pos,pos)};
 }
 function modal(html){root.querySelector('.qa-modal-host').innerHTML=`<div class="qa-modal open"><section class="qa-modal-card"><div class="qa-head"><h3>${selection==='new'?'Nouvelle structure':esc(org(selection)?.name||'Accès personnel')}</h3>${button('Fermer','close')}</div>${html}</section></div>`;motion.syncModal(true,true)}
 const fields={name:'Nom de la structure',city:'Ville',contact:'Nom du responsable',email:'E-mail du responsable'};
 function open(id){selection=id;const o=org(id),l=license(id);modal(`<p>${esc(o.contact_email)} · ${classes(id).length} classes · ${students(id).length} élèves</p><form data-live-form="license"><h4>Licence</h4><div class="qa-form"><label>Formule<select class="qa-select" name="plan">${Object.entries(plans).map(([v,n])=>`<option value="${v}" ${l.plan===v?'selected':''}>${n}</option>`).join('')}</select></label><label>Places élèves<input class="qa-input" name="limit" type="number" min="${Math.max(1,students(id).length)}" max="10000" value="${l.student_limit}" required></label><label>Début<input class="qa-input" name="starts" type="date" value="${l.starts_at}" required></label><label>Fin<input class="qa-input" name="expires" type="date" value="${l.expires_at}" required></label><label>État<select class="qa-select" name="status">${['active','trial','suspended','expired'].map(v=>`<option value="${v}" ${l.status===v?'selected':''}>${names[v]}</option>`).join('')}</select></label><div><button class="qa-button">Enregistrer la licence</button></div></div><p>Aucune facturation automatique. Vous décidez de l’accès accordé.</p></form><hr><form data-live-form="invite"><h4>Donner un accès</h4><label>Nom<input class="qa-input" name="name" value="${esc(o.contact_name)}" required maxlength="80"></label><label>E-mail<input class="qa-input" type="email" name="email" value="${esc(o.contact_email)}" required></label><label>Rôle<select class="qa-select" name="role"><option value="owner">Responsable de la structure</option><option value="teacher">Professeur</option><option value="manager">Gestionnaire</option></select></label><p><button class="qa-button">Créer un lien personnel</button></p><p>Valable 7 jours, réservé à cette adresse. Aucun e-mail n’est envoyé automatiquement.</p></form><div id="invitation-result"></div><a class="qa-button secondary" href="${page('interface.html?organization='+id)}">Voir les classes de cette structure</a>`)}
 async function refresh(){data=await portal('admin_snapshot');render()}
 async function run(fn){if(busy)return;busy=true;root.setAttribute('aria-busy','true');notify('Enregistrement en cours…');try{await fn();notify('Enregistré en ligne.')}catch(e){notify(message(e))}finally{busy=false;root.removeAttribute('aria-busy')}}
 root.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||busy)return;if(b.dataset.tab){tab=b.dataset.tab;query='';render();return}const a=b.dataset.action,id=b.dataset.id;
  if(a==='close'){selection='';root.querySelector('.qa-modal-host').innerHTML='';motion.syncModal(false,true);return}
  if(a==='open')return open(id);
  if(a==='create'){selection='new';modal(`<form data-live-form="organization"><label>Type de compte<select class="qa-select" name="plan" required><option value="class">Professeur — il gère ses classes</option><option value="school">École — le directeur gère ses professeurs</option></select></label><div class="qa-form">${Object.entries(fields).map(([k,label])=>`<label>${label}<input class="qa-input" name="${k}" ${k==='email'?'type="email"':''} maxlength="160" ${k!=='city'?'required':''}></label>`).join('')}</div><p>La structure commence sans licence active. Vous choisirez sa capacité et sa durée.</p><button class="qa-button">Créer la structure</button></form>`);return}
  if(a==='refresh')return run(refresh);
  if(a==='member'){const [organization,profileId]=id.split(':'),m=data.members.find(x=>x.organization_id===organization&&x.profile_id===profileId);if(m.is_active&&!confirm('Suspendre cet accès à la structure ?'))return;return run(async()=>{await portal('set_member',{organization,profile:profileId,role:m.role,active:!m.is_active});await refresh()})}
  if(a==='revoke')return run(async()=>{await portal('revoke_invite',{id});await refresh()});
  if(a==='export')downloadCsv('structures-coran.csv',[['Structure','E-mail','Élèves','Places','État','Fin'],...data.organizations.map(o=>[o.name,o.contact_email,students(o.id).length,license(o.id)?.student_limit,status(license(o.id)),license(o.id)?.expires_at])]);
 });
 root.addEventListener('submit',e=>{const form=e.target.closest('[data-live-form]');if(!form)return;e.preventDefault();const f=Object.fromEntries(new FormData(form));run(async()=>{
  if(form.dataset.liveForm==='organization'){const r=await portal('create_organization',f);await refresh();open(r.id)}
  if(form.dataset.liveForm==='license'){await portal('set_license',{...f,organization:selection});await refresh();open(selection)}
  if(form.dataset.liveForm==='invite'){const r=await portal('invite',{...f,organization:selection});const link=await copyInvitation(r.token);await refresh();root.querySelector('#invitation-result').innerHTML=`<div class="qa-notice"><strong>Lien personnel prêt</strong><p>Copiez-le pour ${esc(f.email)}. Conservez-le maintenant : il ne sera plus affiché après fermeture.</p><input class="qa-input" readonly aria-label="Lien personnel" value="${esc(link)}"></div>`}
 })});
 await refresh();return {refresh,destroy:()=>motion.destroy()};
}
