// Teacher reading and assignment UI; persistence stays with the scoped classroom adapter.
export function mountTeacherCoran(host,{index,classes,currentClass,currentStudent,esc,practice,getPassage,send}){
 let busy=false;
 host.innerHTML=`<section class="cc-card"><h3>📖 Coran · espace professeur</h3><p>Lisez, écoutez puis choisissez un passage à donner à vos élèves.</p><label>Sourate<select id="teacher-surah">${index.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></label><div class="cc-row"><button type="button" id="teacher-whole">Sélectionner toute la sourate</button><button type="button" id="teacher-work" class="cc-primary">Donner à travailler</button></div><div id="cc-practice"></div></section><section class="cc-card" id="teacher-assignment" hidden><h3>Donner à travailler</h3><p id="teacher-passage"></p><form id="teacher-assignment-form"><fieldset><label>Classe<select name="classId" required>${classes.map(c=>`<option value="${esc(c.id)}" ${c.id===currentClass?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><div id="teacher-recipients"></div><label>Objectif<select name="kind"><option value="learn">À apprendre</option><option value="review">À réviser</option></select></label><label>Consigne écrite · facultatif<textarea name="note" maxlength="1400" placeholder="Écoutez ce passage, puis répétez-le à votre rythme."></textarea></label><label>Consigne audio · facultatif<input type="file" name="audio" accept="audio/*" capture></label><small>Choisissez un audio, ou enregistrez-le si votre téléphone le propose. 25 Mo maximum.</small><p>Le passage sera visible sur l’arbre des élèves choisis. La sourate sera ouverte dans le programme de la classe si nécessaire. Les progrès restent à valider par le professeur.</p><button class="cc-primary" ${classes.length?'':'disabled'}>Envoyer aux élèves sélectionnés</button></fieldset></form><p id="teacher-send-status" role="status" aria-live="polite"></p></section>`;
 const select=host.querySelector('#teacher-surah'),panel=host.querySelector('#teacher-assignment'),form=host.querySelector('form'),status=host.querySelector('#teacher-send-status');
 function recipients(){const c=classes.find(c=>c.id===form.elements.classId.value);host.querySelector('#teacher-recipients').innerHTML=`<fieldset><legend>Élèves</legend><label class="cc-check"><input type="checkbox" id="teacher-all"> Toute la classe</label>${(c?.students||[]).map(s=>`<label class="cc-check"><input type="checkbox" name="students" value="${esc(s.id)}" ${c.id===currentClass&&s.id===currentStudent?'checked':''}> ${esc(s.name)}</label>`).join('')||'<p>Ajoutez des élèves dans cette classe pour leur donner du travail.</p>'}</fieldset>`;host.querySelector('#teacher-all').onchange=e=>form.querySelectorAll('[name="students"]').forEach(i=>i.checked=e.target.checked);form.querySelectorAll('[name="students"]').forEach(i=>i.onchange=()=>{const inputs=[...form.querySelectorAll('[name="students"]')],all=host.querySelector('#teacher-all');all.checked=inputs.length>0&&inputs.every(i=>i.checked);all.indeterminate=inputs.some(i=>i.checked)&&!all.checked})}
 form.elements.classId.onchange=recipients;recipients();
 form.addEventListener('change',()=>{if(!busy){form.querySelector('button').disabled=!classes.length;status.textContent=''}});
 select.onchange=()=>{panel.hidden=true;practice(Number(select.value))};
 host.querySelector('#teacher-whole').onclick=()=>{panel.hidden=true;const s=index.find(s=>s.id===Number(select.value));practice(s.id,1,s.count)};
 host.querySelector('#teacher-work').onclick=()=>{const p=getPassage();if(!p||p.id!==Number(select.value))return;panel.hidden=false;status.textContent='';form.querySelector('button').disabled=!classes.length;host.querySelector('#teacher-passage').textContent=`${index.find(s=>s.id===p.id).name} · versets ${p.from} à ${p.to}`;panel.scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})};
 host.querySelector('#cc-practice').addEventListener('click',e=>{if(e.target.closest('[data-reader="verse"], [data-reader="whole"]'))panel.hidden=true});
 form.onsubmit=async e=>{e.preventDefault();e.stopPropagation();if(busy)return;const f=new FormData(form),p=getPassage();if(!p)return;const ids=f.getAll('students');if(!ids.length){status.textContent='Choisissez au moins un élève.';return}const file=f.get('audio');if(file?.size&&(!file.type.startsWith('audio/')||file.size>25*1024*1024)){status.textContent='Choisissez un fichier audio de moins de 25 Mo.';return}busy=true;form.querySelector(':scope > fieldset').disabled=true;select.disabled=true;host.querySelector('#teacher-whole').disabled=true;host.querySelector('#teacher-work').disabled=true;status.textContent='Envoi en cours…';try{await send({classId:f.get('classId'),ids,passage:{...p},kind:f.get('kind'),note:f.get('note'),audio:file?.size?file:null});status.textContent=`Passage envoyé à ${ids.length} élève(s).`;form.querySelector('button').disabled=true}catch(error){status.textContent=error.message}finally{busy=false;form.querySelector(':scope > fieldset').disabled=false;select.disabled=false;host.querySelector('#teacher-whole').disabled=false;host.querySelector('#teacher-work').disabled=false}};
 practice(Number(select.value));
}
