-- Kawaii Muslim World — statistiques anonymes de fréquentation
-- Déjà activé sur le projet Supabase le 8 septembre 2026.
begin;
create table if not exists public.site_visits (
  id bigint generated by default as identity primary key,
  visitor_id text not null check (char_length(visitor_id) between 16 and 80),
  visit_day date not null default (timezone('Europe/Paris', now()))::date,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  path text not null default '/',
  referrer_host text not null default '',
  device text not null default 'desktop' check (device in ('mobile','tablet','desktop'))
);
create unique index if not exists site_visits_visitor_day_unique on public.site_visits(visitor_id, visit_day);
create index if not exists site_visits_day_idx on public.site_visits(visit_day desc);
alter table public.site_visits enable row level security;
revoke all on public.site_visits from public, anon, authenticated;
create or replace function public.track_site_visit(p_visitor_id text, p_path text default '/', p_referrer_host text default '', p_device text default 'desktop')
returns void language plpgsql security definer set search_path=public as $$
declare v_day date := (timezone('Europe/Paris', now()))::date;
begin
  if p_visitor_id is null or char_length(p_visitor_id) < 16 or char_length(p_visitor_id) > 80 then return; end if;
  insert into public.site_visits(visitor_id,visit_day,path,referrer_host,device)
  values(p_visitor_id,v_day,left(coalesce(p_path,'/'),240),left(coalesce(p_referrer_host,''),160),
    case when p_device in ('mobile','tablet','desktop') then p_device else 'desktop' end)
  on conflict(visitor_id,visit_day) do update set last_seen_at=now(),path=excluded.path,referrer_host=excluded.referrer_host,device=excluded.device;
end; $$;
create or replace function public.admin_site_visit_stats()
returns jsonb language plpgsql stable security definer set search_path=public as $$
declare v_today date := (timezone('Europe/Paris',now()))::date; v_result jsonb;
begin
  if not public.is_admin() then raise exception 'Accès administrateur requis'; end if;
  select jsonb_build_object('today',count(*) filter(where visit_day=v_today),'days7',count(*) filter(where visit_day>=v_today-6),
    'days30',count(*) filter(where visit_day>=v_today-29),'total',count(distinct visitor_id),'updated_at',now())
  into v_result from public.site_visits;
  return v_result;
end; $$;
revoke all on function public.track_site_visit(text,text,text,text) from public;
grant execute on function public.track_site_visit(text,text,text,text) to anon,authenticated;
revoke all on function public.admin_site_visit_stats() from public,anon;
grant execute on function public.admin_site_visit_stats() to authenticated;
commit;
