import test from 'node:test';
import assert from 'node:assert/strict';
import {createDemoMessaging} from '../applications/classroom/messaging-data.mjs';
import {createCloudClassroom} from '../applications/classroom/cloud-classroom.mjs';
function setup(){const map=new Map(),classes=[{id:'c',students:[{id:'s',name:'Élève'},{id:'other',name:'Autre'}]},{id:'off',students:[]}];const request=createDemoMessaging({key:'qa',storage:{getItem:k=>map.get(k),setItem:(k,v)=>map.set(k,v)},getClasses:()=>classes});return {request,teacher:{role:'teacher',name:'Professeur'},student:{role:'student',name:'Élève',studentId:'s'}}}
test('messaging is opt-in per class; only the teacher can configure it',async()=>{const {request,teacher,student}=setup();assert.equal((await request('status',{},teacher)).classes[0].enabled,false);await assert.rejects(request('configure',{class:'c',enabled:true},student));await request('configure',{class:'c',enabled:true},teacher);const state=await request('status',{},teacher);assert.equal(state.classes[0].enabled,true);assert.equal(state.classes[1].enabled,false)});
test('private replies, idempotent retries, unread markers and disable/re-enable history',async()=>{const {request,teacher,student}=setup();await request('configure',{class:'c',enabled:true},teacher);const payload={id:'m',student:'s',text:'Bonjour'};const sent=await request('send',payload,teacher);await request('send',payload,teacher);assert.equal((await request('thread',{student:'s'},student)).messages.length,1);assert.equal((await request('status',{},student)).classes[0].unread,1);await request('read',{student:'s',sequence:1e6},student);assert.equal((await request('status',{},student)).classes[0].unread,0);const next=await request('send',{...payload,id:'m2'},teacher);assert.ok(next.sequence>sent.sequence);assert.equal((await request('status',{},student)).classes[0].unread,1);await assert.rejects(request('thread',{student:'other'},student));await request('configure',{class:'c',enabled:false},teacher);await assert.rejects(request('send',{...payload,id:'m3'},student));await request('configure',{class:'c',enabled:true},teacher);assert.equal((await request('thread',{student:'s'},student)).messages.length,2)});
test('pagination covers history and text/audio validation',async()=>{const {request,teacher,student}=setup();await request('configure',{class:'c',enabled:true},teacher);for(let i=0;i<105;i++)await request('send',{id:String(i),student:'s',text:'Message '+i},teacher);const page=await request('thread',{student:'s'},student);assert.equal(page.messages.length,100);assert.equal(page.hasOlder,true);const old=await request('thread',{student:'s',before:page.messages[0].sequence},student);assert.equal(old.messages.length,5);assert.equal(old.hasOlder,false);await assert.rejects(request('send',{id:'empty',student:'s',text:' '},student));await assert.rejects(request('send',{id:'long',student:'s',text:'a'.repeat(3001)},student));const audio=await request('send',{id:'vocal',student:'s',audioId:'audio'},student);assert.equal(audio.role,'student');assert.equal(audio.audioId,'audio')});
test('cloud messages use a separate authenticated RPC and never the garden save queue',async()=>{const calls=[];const cloud=createCloudClassroom('org',{rpc:()=>{throw Error('wrong RPC')},messagingRpc:async(action,payload)=>{calls.push({action,payload});return {saved:true}}});await cloud.message('send',{student:'s',text:'Bonjour',organization:'forged'});assert.deepEqual(calls,[{action:'send',payload:{student:'s',text:'Bonjour',organization:'org'}}]);assert.equal(cloud.pending,0)});
