import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {cleanProgress,createSession,completeVerse,earnTree,parentPlan,matches,splitBasmala} from '../applications/coran/model.mjs';
import {QuranPlayer} from '../applications/coran/audio.mjs';
const index=JSON.parse(await readFile(new URL('../applications/coran/data/index.json',import.meta.url),'utf8'));
test('entire corpus: 114 chapters, 6236 aligned unique verse and audio references',async()=>{
 let global=0;assert.equal(index.length,114);
 for(const s of index){const c=JSON.parse(await readFile(new URL(`../applications/coran/data/${s.id}.json`,import.meta.url),'utf8'));assert.equal(c.verses.length,s.count);for(const v of c.verses){assert.equal(v.number,++global);assert.equal(v.id,`${s.id}:${v.verse}`);assert.ok(v.arabic.length);assert.ok(v.translation.length);assert.equal(v.audio,`https://cdn.islamic.network/quran/audio/128/ar.hudhaify/${global}.mp3`);}}
 assert.equal(global,6236);assert.equal(index[1].count,286);assert.equal(index[113].count,6);
});
test('legacy exploration migrates without claiming memorization or losing progress',()=>{const p=cleanProgress({version:1,completed:['112:1','112:1'],verse:2},index);assert.equal(Object.keys(p.completed).length,1);assert.deepEqual(p.lastRead,{surah:112,verse:3});assert.equal(p.completed['112:1'].due,0)});
test('invalid saved state falls back safely',()=>{const p=cleanProgress({goal:'bad',lastRead:{surah:999,verse:2},bookmarks:['2:286','2:287',null,'2:286'],completed:{'2:287':{times:1,last:0,due:0}},session:{items:[{surah:1,verse:88}],position:0,step:0}},index);assert.deepEqual(p.bookmarks,['2:286']);assert.equal(p.session,null);assert.equal(p.goal,'discover');assert.deepEqual(p.lastRead,{surah:1,verse:1})});
test('sessions offer one due review and one new verse; missed days never remove progress',()=>{let p=cleanProgress(null,index);assert.equal(createSession(p,index,0).items[0].surah,1);p=completeVerse(p,{surah:1,verse:1},0);assert.equal(p.completed['1:1'].due,86400000);const s=createSession(p,index,86400001);assert.deepEqual(s.items,[{surah:1,verse:1,review:true},{surah:1,verse:2,review:false}]);const q=completeVerse(p,{surah:1,verse:1},86400001);assert.equal(q.completed['1:1'].times,2);assert.equal(q.completed['1:1'].due,86400001+3*86400000)});
test('ten repetitions in Coran can earn one tree and refresh its seven-day date',()=>{let p=cleanProgress(null,index);p=earnTree(p,{surah:113,verse:1},100);assert.deepEqual(p.treeEarned,['113:1']);assert.equal(p.treeReview['113:1'],100);p=earnTree(p,{surah:113,verse:1},200);assert.deepEqual(p.treeEarned,['113:1']);assert.equal(p.treeReview['113:1'],200);assert.equal(p.completed['113:1'].times,2)});
test('parent moments partition any surah without missing or duplicating a verse',()=>{for(const s of index){const plan=parentPlan(s.count),covered=plan.flatMap(d=>Array.from({length:d.to-d.from+1},(_,i)=>d.from+i));assert.equal(covered.length,s.count);assert.equal(new Set(covered).size,s.count);assert.equal(covered[0],1);assert.equal(covered.at(-1),s.count);assert.ok(plan.length<=5)}});
test('search supports diacritics, Arabic and exact chapter numbers',()=>{assert.ok(matches(index[0],'fati'));assert.ok(matches(index[0],'فاتحة'));assert.ok(matches(index[113],'114'))});
class FakeAudio extends EventTarget {constructor(){super();this.paused=true;this.currentTime=0;this.duration=8;this.ended=false;}pause(){this.paused=true}removeAttribute(){this.src=''}load(){}async play(){this.paused=false} }
const queue=[{id:'1:1',audio:'one'},{id:'1:2',audio:'two'}];
test('audio sequence advances and stops at its end',async()=>{const a=new FakeAudio,p=new QuranPlayer(a,()=>{});p.start(queue);await Promise.resolve();assert.equal(p.current.id,'1:1');a.dispatchEvent(new Event('ended'));await Promise.resolve();assert.equal(p.current.id,'1:2');a.dispatchEvent(new Event('ended'));assert.equal(p.state,'ended');p.stop();assert.equal(p.current,null)});
test('repetitions keep the same verse and stop; pause cancels scheduled silence',async()=>{const a=new FakeAudio,p=new QuranPlayer(a,()=>{});p.start(queue.slice(0,1),{repeat:3});await Promise.resolve();a.dispatchEvent(new Event('ended'));await Promise.resolve();assert.equal(p.round,1);a.dispatchEvent(new Event('ended'));await Promise.resolve();assert.equal(p.round,2);a.dispatchEvent(new Event('ended'));assert.equal(p.state,'ended');p.start(queue,{repeat:3,gap:true});await Promise.resolve();a.dispatchEvent(new Event('ended'));assert.equal(p.state,'gap');await p.toggle();assert.equal(p.timer,null);assert.equal(p.state,'paused');p.stop()});
test('the automatic repetition pause is exactly two seconds',async t=>{t.mock.timers.enable({apis:['setTimeout']});const a=new FakeAudio,p=new QuranPlayer(a,()=>{});p.start(queue.slice(0,1),{repeat:2,gap:true});await Promise.resolve();p.ended();t.mock.timers.tick(1999);assert.equal(p.round,0);t.mock.timers.tick(1);assert.equal(p.round,1);p.stop()});
test('there is no extra pause after the final repetition',async()=>{const a=new FakeAudio,p=new QuranPlayer(a,()=>{});p.start(queue.slice(0,1),{repeat:1,gap:true,gapSeconds:2});await Promise.resolve();p.ended();assert.equal(p.state,'ended');assert.equal(p.timer,null);p.stop()});
test('audio load rejection exposes retry rather than pretending it played',async()=>{const a=new FakeAudio;a.play=async()=>{throw new Error('network')};const p=new QuranPlayer(a,()=>{});p.start(queue);await Promise.resolve();assert.equal(p.state,'error');p.stop()});
test('stale play promises cannot restart state after stopping',async()=>{const a=new FakeAudio;let finish;a.play=()=>new Promise(r=>{finish=r});const p=new QuranPlayer(a,()=>{});p.start(queue);p.stop();finish();await Promise.resolve();assert.equal(p.state,'idle');assert.equal(p.current,null)});
test('basmala display separation preserves every source character',async()=>{for(const s of index){const c=JSON.parse(await readFile(new URL(`../applications/coran/data/${s.id}.json`,import.meta.url),'utf8'));const v=c.verses[0],parts=splitBasmala(v);assert.equal(parts.preface+parts.text,v.arabic);if(s.id===1||s.id===9)assert.equal(parts.preface,'');else assert.ok(parts.preface.length>0)}});
test('same-reciter fallback retries once per source then exposes failure',async()=>{const a=new FakeAudio;const sources=[];a.play=async()=>{sources.push(a.src);throw new Error('temporary CDN error')};const p=new QuranPlayer(a,()=>{});p.start([{id:'1:1',audio:'128',audioSecondary:['64','32']}]);for(let i=0;i<5;i++)await Promise.resolve();assert.deepEqual(sources,['128','64','32']);assert.equal(p.state,'error');p.stop()});
test('whole passage repeats in order and stops after selected rounds',async()=>{const a=new FakeAudio(),p=new QuranPlayer(a,()=>{});p.start([2,3,4,5].map(n=>({id:String(n),audio:String(n)})),{passageRepeat:3});const heard=[];for(let i=0;i<12;i++){await Promise.resolve();heard.push(p.current.id);p.ended()}assert.deepEqual(heard,['2','3','4','5','2','3','4','5','2','3','4','5']);assert.equal(p.state,'ended');p.stop()});
test('custom silence uses selected seconds and stopping cancels it',async t=>{t.mock.timers.enable({apis:['setTimeout']});const a=new FakeAudio(),p=new QuranPlayer(a,()=>{});p.start([{id:'2',audio:'2'},{id:'3',audio:'3'}],{gap:true,gapSeconds:5});await Promise.resolve();p.ended();assert.equal(p.state,'gap');t.mock.timers.tick(4999);assert.equal(p.current.id,'2');t.mock.timers.tick(1);assert.equal(p.current.id,'3');await Promise.resolve();p.ended();p.stop();t.mock.timers.tick(5000);assert.equal(p.current,null)});
